### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by MatiasBjorling**

### CODE REVIEW

**Comment by safl** [comment]
This looks good, the "Fix up LBA backend" spawns a couple of questions that I hope you can help answer:

* Why is BLKDISCARD preferred over OCSSD erase/reset?
* What are the kernel requirements for IO via the blk device in this form? Specifically, which kernel version supports IO via offset and from which kernel version is the BLKDISCARD transformed into OCSSD erase/reset?

Thanks!

**Comment by MatiasBjorling** [comment]
BLKDISCARD correspond to DSM in NVMe. It's is mandatory in OCSSD, while the vector erase is optional
There is no need to convert BLKDISCARD into OCSSD erase, it should already be supported by the drive.

**Comment by safl** [comment]
I see that makes sense. Can you elaborate on the kernel requirements? The reason I ask is that I want to expand documentation and testing for the different backends. Especially the LBA, as it has received very little attention in these areas.

**Comment by MatiasBjorling** [comment]
It requires BLKDISCARD support. It has been part of the kernel for the last 8 years. I think we are safe.

**Comment by safl** [comment]
@MatiasBjorling Great. What about read/write? Are they merely mapped, in the kernel, to the NVMe READ(0x2)/WRITE(0x1) and thus supported ever since the NVMe driver supported the opcodes? So, no LightNVM subsystem in that path either?

**Comment by MatiasBjorling** [comment]
Correct.

**Comment by javigon** [comment]
You need an address conversion somewhere. Isn't LightNVM the most intuitive place to put this, given that it knows the format through the geometry?

**Comment by MatiasBjorling** [comment]
No. liblightnvm knows the geometry. That is why we can have a lba and a spdk backends.

**Comment by javigon** [comment]
Sure. liblightnvm is good; I'm thinking of the kernel path. Seems to me that the discussion has shifted to normal nvme support. But we can take this when you submit the zone patches to the kernel.

**Comment by MatiasBjorling** [comment]
I see these as orthogonal. liblightnvm already knows the geometry and can issue I/O appropriately.

If you want to checkout the zone support, you can lookup the for-4.19/zoned branch.

**Comment by javigon** [comment]
I’ll look at the patches later. 

One thing that is not clear to me in liblightnvm is how you deal with address checks in the normal I/O path. The device format might cause addresses to go out of range. Am I missing something?

**Comment by MatiasBjorling** [comment]
Why would they go out of range? :)

**Comment by javigon** [comment]
Nothing would prevent a device to report a larger sector/chunk/PU area than needed and push groups to a bit higher than the device’s size. I would assum that an I/O to such an address would be detected as out of range. Right?

**Comment by MatiasBjorling** [comment]
If reading from an unmapped LBA, it depends on the error recovery feature
value. If not set, empty data is returned and else out of range error is
returned.

tor. 28. jun. 2018 16.07 skrev Javier Gonzalez <notifications@github.com>:

**Comment by javigon** [comment]
That’s not what I meant. I mean an address that is valid for liblightnvm and valid for the device. If using the nvme ioctl path, the address might seem out of range for the nvme driver because of the address format itself. If using SPDK or the lightnvm ioctls, this is not a problem.

**Comment by MatiasBjorling** [comment]
No. The size of the drive is such that all chunks can be accessed.

**Comment by MatiasBjorling** [comment]
I can't do anything about the addressing scheme for OCSSD 2.0 at this point. Also note, this is the same being done for vector commands. So it not new, you may not have thought of it this way.

Usually, this detail goes into the SSD drive spec.

**Comment by javigon** [comment]
To me the vector interface is a different story because it has it's own path, so checks at the address level are different from the normal path and understand the hierarchical model. But yes, this has been a problem in 2.0 since the beginning (we discussed it back in the days) and we need to deal with it now. For liblightnvm specifically, it would make sense to have checks on the available device size at initialization, to avoid I/O errors if using the normal nvme path.

**Comment by MatiasBjorling** [comment]
I don't know if it has been a problem. It is more a natural effect of the addressing scheme that is in place. This applies both for NVMe Read/Write and Vector Read/Write. The addressing is the same.  The drive model/addressing and the I/O mechanisms are orthogonal. That there are different paths inside the Linux kernel is not important. Look at the ioctl code, there are no boundary checks performed by the kernel for the vector ioctl path. It is all assumed that the caller issues the appropriate LBAs.

There is no need for a size check. It is a broken implementation if it reports the wrong size.

**Comment by MatiasBjorling** [comment]
No, it is not linear and shall not be linear. For example, look at the get log page chunk information. There are not two SLBA's reported. Only one, and that should be the same LBA that is used by both NVMe Read/Write and Vector Read/Write.

For the size argument, that is what the NCAP field is for within the NVM Command Set identity section is for.

**Comment by javigon** [comment]
It's not linear, exactly my point. Thus, checks on the disk capacity _might_ fail if assuming a linear space. This goes beyond chunk->slba + len < chunk->cnlb; it is about lba (GR/PU/CHK/SECT) < size.

NCAP defines the namespace capacity, and explicitly defines that spare LBAs are not to be reported.

Anyway, as mentioned, this goes beyond this particular PR; we can take it in a different context.

**Comment by javigon** [comment]
Nvme address format is linear, the OCSSD one not. That is the point, that without extra effort they are not directly compatible. Do not transverse what is being said, please.

NCAP: "This field indicates the maximum number of logical blocks that may be allocated in the namespace at any point in time. The number of logical blocks is based on the formatted LBA size. This field is undefined prior to the namespace being formatted. This field is used in the case of thin provisioning and reports a value that is smaller than or equal to the Namespace Size. Spare LBAs are not reported as part of this field." -> My understanding is that the size is given in logical blocks. If I give you 4, then size is from 0-3, and check will be lba < 0, independently of the encoding of the lba. You might have a different version of the spec...

**Comment by safl** [comment]
@Matias, thanks for the PR, it leaves the LBA backend in a better state than it was. Thanks to both of you for the information/discussion BLK IO and the address-encoding challenges. I'll pull in the changes and leave PR open for the next day or so if anybody has something they would like to add.

**Comment by MatiasBjorling** [comment]
That is not exactly true. For vector I/O read/write, they still work within the linear address space of the NVM Command Set. What the OCSSD specification defines is a projection of a hierarchical structure on top of it. 

The NCAP field is not used for the size of the drive in the stack, that is the NSZE attribute. Which is the one the kernel will check boundaries for.

**Comment by javigon** [comment]
Let me put it differently: On a nvme device, it is assumed that all is in a linear address space, but on an OCSSD we cannot make that assumption. Thus, if OCSSD is to be integrated on the generic path some parts about the hierarchical address space would need to be understood. 

We can play with the parameters reported by the device, but IMHO, reporting a false, large size and or is not a good idea. Think that these values go directly to user space - how are you going to explain to a customer that a device advertises 16TB, when she only can use 4TB? 

Anyway, as much as I like discussing with you, this conversation goes beyond this thread. Let's take it somewhere else :)

**Comment by MatiasBjorling** [comment]
That is where liblightnvm comes in and is the reason for this patch. But
there does not need to be any checks in the kernel other than the ones
already there.

For NSZE/NCAPAs, it is inherent to the addressing mode used in the OCSSD
spec. It should be easy to explain, it has been like this from the early
days and is a direct tradeoffs of exposing the CH/GRP/CHK addressing.

**Pull request merged**
